language: go

go:
  - 1.3
  - 1.4
  - tip

script: 
 - go test -v -cpu=1,2,4 .
 - go test -v -cpu=1,2,4 -race .
 - go test -v -cpu=2 ./drivers/boltpw
 - go test -v -cpu=2 ./drivers/testdb
 - diff <(gofmt -d .) <("")
