language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

services:
  - mongodb

before_script:
  - mysql -e 'create database testdb;'
  - psql -c 'create database testdb;' -U postgres

script: 
 - go test -v -cpu=1,2,4 .
 - go test -v -cpu=1,2,4 -race .
 - go test -v -cpu=2 -race ./drivers/testdb
 - go test -v -cpu=2 -race ./drivers/boltpw
 - go test -v -cpu=2 -race ./drivers/mgopw
 - go test -v -cpu=2 -race ./drivers/sqlpw
 - go test -v -cpu=2 -race ./drivers/bloompw
 - diff <(gofmt -d .) <("")
