language: go

sudo: false

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

services:
  - mongodb
  - cassandra

before_script:
  - mysql -e 'create database testdb;'
  - psql -c 'create database testdb;' -U postgres
  - "echo \"create keyspace testkeyspace with replication = {'class':'SimpleStrategy','replication_factor':1};\" | /usr/local/cassandra/bin/cqlsh --cqlversion=3.0.3"

install:
 - go get -t ./...
 - go get -u golang.org/x/tools/cmd/goimports

script: 
 - go vet ./...
 - diff <(goimports -d .) <(printf "")
 - go test -v -cpu=1,2,4 .
 - go test -v -cpu=1,2,4 -race .
 - go test -v -cpu=2 -race ./drivers/testdb
 - go test -v -cpu=2 -race ./drivers/boltpw
 - go test -v -cpu=2 -race ./drivers/mgopw
 - go test -v -cpu=2 -race ./drivers/sqlpw
 - go test -v -cpu=2 -race ./drivers/bloompw
 - go test -v -cpu=2 -race ./drivers/cassandra
